services:
     
  opensearch-node1:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_master_nodes=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1
  
  data-prepper:
    image: opensearchproject/data-prepper:1.5.1
    volumes:
      - ./data-prepper-pipelines.yml:/usr/share/data-prepper/pipelines.yaml
      - ./data-prepper-config.yml:/usr/share/data-prepper/data-prepper-config.yaml
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1
  
  otel-collector:
    image: amazon/aws-otel-collector:v0.21.1
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55670:55679" # zpages extension
    expose:
      - "4317"
      - "4318"
    networks:
      - opensearch-net
    depends_on:
      - data-prepper

  ecom-user:
    image: ecom-user:latest
    volumes:
      - ./tomcat/logs:/tomcat/logs
    ports:
      - "8080:8080"   # pprof extension
    expose:
      - "8080"
    depends_on:
      - otel-collector
    environment:
      - AD_SERVICE_PORT
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
      - OTEL_SERVICE_NAME=ecom-user
    networks:
      - opensearch-net
      
      
  ecom-user:
    image: ecom-user:latest
    volumes:
      - ./tomcat/logs:/tomcat/logs
    ports:
      - "8080:8080"   # pprof extension
    expose:
      - "8080"
    depends_on:
      - otel-collector
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=ecom-user,service.namespace=ECom
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
       
  
volumes:
  opensearch-data1:

networks:
  opensearch-net:
  