services:
 
  data-prepper:
    image: opensearchproject/data-prepper:2.5.0
    volumes:
      - ./data-prepper-pipelines.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./data-prepper-config.yml:/usr/share/data-prepper/config/data-prepper-config.yaml
    ports:
      - 21890:21890
      - 21891:21891
    expose:
      - "21890"
      - "21891"
    networks:
      - opensearch-net
  
networks:
  opensearch-net:
  
  